defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.pretrain.train_diffusion_agent.TrainDiffusionAgent

name: ${env}_pre_diffusion_equiunet_img_ta${horizon_steps}_td${denoising_steps}
logdir: ${oc.env:DPPO_LOG_DIR}/robomimic-pretrain/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
train_dataset_path: ${oc.env:DPPO_DATA_DIR}/robomimic/${env}-img/train.npz

seed: 42
device: cuda:0
env: can
obs_dim: 9  # proprioception: pos(3) + quat(4) + gripper_qpos(2)
action_dim: 10  # FIXED: xyz(3) + rot6d(6) + gripper(1) after conversion
denoising_steps: 100
horizon_steps: 4
cond_steps: 1
img_cond_steps: 1

wandb:
  entity: ${oc.env:DPPO_WANDB_ENTITY}
  project: robomimic-${env}-pretrain-equi
  run: ${now:%H-%M-%S}_${name}
  
shape_meta:
  obs:
    rgb:
      shape: [3, 96, 96]  # not counting img_cond_steps
    state:
      shape: [9]
  action: 
    shape: [10]  # FIXED: must match action_dim

train:
  n_epochs: 500
  batch_size: 32
  learning_rate: 1e-4
  weight_decay: 1e-6
  lr_scheduler:
    first_cycle_steps: 2000
    warmup_steps: 100
    min_lr: 1e-5
  save_model_freq: 100

model:
  _target_: model.diffusion.diffusion.DiffusionModel
  predict_epsilon: True
  denoised_clip_value: 1.0
  network:
    _target_: model.diffusion.Equi_Unet.EquiDiffusionUNet
    act_emb_dim: 64  
    local_cond_dim: null
    global_cond_dim: 128  # per-orbit feature dim; becomes 128*8=1024 total, then split back
    diffusion_step_embed_dim: 256
    down_dims: [256, 512, 1024]
    kernel_size: 3
    n_groups: 8
    cond_predict_scale: false
    N: 8
  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}  # Now correctly 10
  denoising_steps: ${denoising_steps}
  device: ${device}

ema:
  decay: 0.995

train_dataset:
  _target_: agent.dataset.sequence.StitchedSequenceDataset
  use_img: True
  dataset_path: ${train_dataset_path}
  horizon_steps: ${horizon_steps}
  max_n_episodes: 20
  cond_steps: ${cond_steps}
  img_cond_steps: ${img_cond_steps}
  device: ${device}
  convert_to_rot6d: True  # Converts 7D axis-angle actions to 10D rot6d
