defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.pretrain.train_diffusion_agent.TrainDiffusionAgent

name: ${env}_pre_diffusion_equiunet_img_ta${horizon_steps}_td${denoising_steps}
logdir: ${oc.env:DPPO_LOG_DIR}/robomimic-pretrain/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
train_dataset_path: ${oc.env:DPPO_DATA_DIR}/robomimic/${env}-img/train.npz
normalization_path: ${oc.env:DPPO_DATA_DIR}/robomimic/${env}-img/normalization.npz

seed: 42
device: cuda:0
env: lift
obs_dim: 9  # proprioception only
action_dim: 10  # xyz + rot6d + gripper
denoising_steps: 100
horizon_steps: 4
cond_steps: 1
img_cond_steps: 1

wandb: null  # disable wandb in sandbox; set entity/project/run to enable

shape_meta:
  obs:
    rgb:
      shape: [3, 96, 96]  # not counting img_cond_steps
    state:
      shape: [9]
  action: 
    shape: [10]

train:
  n_epochs: 500
  batch_size: 128
  learning_rate: 1e-4
  weight_decay: 1e-6
  lr_scheduler:
    first_cycle_steps: 2000
    warmup_steps: 100
    min_lr: 1e-5
  save_model_freq: 100

model:
  _target_: model.diffusion.diffusion.DiffusionModel
  predict_epsilon: True
  denoised_clip_value: 1.0
  network:
    _target_: model.diffusion.Equi_Unet.EquiDiffusionUNet
    act_emb_dim: 64  
    local_cond_dim: null
    global_cond_dim: 128             # per-orbit feature dim (n_hidden); flattened per order inside model
    diffusion_step_embed_dim: 256
    down_dims: [256, 512, 1024]
    kernel_size: 3
    n_groups: 8
    cond_predict_scale: false
    N: 8
  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  denoising_steps: ${denoising_steps}
  device: ${device}

ema:
  decay: 0.995

train_dataset:
  _target_: agent.dataset.sequence.StitchedSequenceDataset
  use_img: True
  dataset_path: ${train_dataset_path}
  horizon_steps: ${horizon_steps}
  max_n_episodes: 100
  cond_steps: ${cond_steps}
  img_cond_steps: ${img_cond_steps}
  device: ${device}
  convert_to_rot6d: True
  normalization_path: ${normalization_path} 
  denormalize_obs: True                                       
